import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3c4a42',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        primary: '#006c49',
        'on-primary': '#ffffff',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'inverse-primary': '#4edea3',
        secondary: '#2b6954',
        'on-secondary': '#ffffff',
        'secondary-container': '#adedd3',
        'on-secondary-container': '#306d58',
        'secondary-fixed': '#b0f0d6',
        'secondary-fixed-dim': '#95d3ba',
        tertiary: '#a43a3a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#fc7c78',
        'on-tertiary-container': '#711419',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3af',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#6c7a71',
        'outline-variant': '#bbcabf',
        'surface-tint': '#006c49',
        'surface-variant': '#d3e4fe',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        xl: '80px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
