import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fcf8fb',
        surface: '#fcf8fb',
        'surface-dim': '#dcd9dc',
        'surface-bright': '#fcf8fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f5',
        'surface-container': '#f0edef',
        'surface-container-high': '#eae7ea',
        'surface-container-highest': '#e4e2e4',
        'on-surface': '#1b1b1d',
        'on-surface-variant': '#414755',
        'inverse-surface': '#303032',
        'inverse-on-surface': '#f3f0f2',
        primary: '#0058bc',
        'on-primary': '#ffffff',
        'primary-container': '#0070eb',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'inverse-primary': '#adc6ff',
        secondary: '#8c5000',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe9400',
        'on-secondary-container': '#633700',
        'secondary-fixed': '#ffdcbf',
        'secondary-fixed-dim': '#ffb874',
        tertiary: '#5a5c60',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#737479',
        'on-tertiary-container': '#1a1c1f',
        'tertiary-fixed': '#e2e2e7',
        'tertiary-fixed-dim': '#c6c6cb',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#717786',
        'outline-variant': '#c1c6d7',
        'surface-tint': '#0058bc',
        'surface-variant': '#e4e2e4',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        xl: '80px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
